### ISSUE TITLE
Doesn't kill the process

### ISSUE THREAD

**Issue by Integralist** [pjmp/ikill#1]
👋🏻 

Just wanted to share that I've tried this a couple of ways and it appears to not kill the process.

> **NOTE**: I'm running macOS.

The following is a quick screen recording to show what I'm doing...

https://asciinema.org/a/Ay1lRYPtdjS1z5xrVaVuU9I8q

Even though I select the process to kill it stays present.

Thanks.

**Comment by pombadev** [comment]
Hello, I don't have a mac to test this out, I'll see if I can get a mac vm and debug.
Thank you for taking time to report this!
